stages:
  - deploy

pages:
  stage: deploy
  script:
    - sed -E 's/href="slides\/(.*)"/href="\1.html"/g' views/index.ejs > public/index.html
    - for f in ./public/slides/*.md; do FILENAME=$(echo "${f##*/}" | sed 's/\.[^.]*$//'); sed 's/<%= session %>/slides\/'"$FILENAME"'/g' views/slides.ejs > public/$FILENAME.html ; done
    - for f in ./public/*.html; do sed -i 's/base href="/"/base href="'$CI_PAGES_URL'"/g' $f ; done
  artifacts:
    paths:
      - public
  only:
    - master
